export default {
  openAssignmentModal: "OPEN_ASSIGNMENT_MODAL",
  setAssignment: "SET_ASSIGNMENT",
  setGroup: "SET_GROUP",
  setDueDate: "SET_DUE_DATE",
  setExercise: "SET_EXERCISE",
  setAssignments: "SET_ASSIGNMENTS",
  setGroups: "SET_GROUPS",
  openGroupModal: "OPEN_GROUP_MODAL",
  setExercises: "SET_EXERCISES",
  setGroupSelected: "SET_GROUP_SELECTED",
  openExerciseModal: "OPEN_EXERCISE_MODAL",
  setExerciseSelected: "SET_EXERCISE_SELECTED",
  setAction: "SET_ACTION",
};
